# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { 'moana.yamanouchi' } %>
  password: <%= ENV['DATABASE_PASSWORD'] %> # variable previously added
  host: localhost  # <--- THIS IS THE KEY
  port: 5432

development:
  <<: *default
  database: the-odin-project_development  # Change 'the-odin-project' to your project name

test:
  <<: *default
  database: the-odin-project_test         # Change 'the-odin-project' to your project name

production:
  primary:
    <<: *default
    database: the-odin-project_production
    username: the-odin-project
    password: <%= ENV["the-odin-project_DATABASE_PASSWORD"] %>
  # You can keep the cache/queue/cable blocks if you need them for Rails 7+,
  # just ensure they use the postgresql adapter via the *default anchor.
  cache:
    <<: *default
    database: the-odin-project_production_cache
  queue:
    <<: *default
    database: the-odin-project_production_queue
  cable:
    <<: *default
    database: the-odin-project_production_cable